#macro m_version 1
#macro m_vel_dia 1.5
#macro m_dificultad 5
#macro m_comida_humano 4
#macro m_respawn_s 5
#macro m_refinar_s 5
#macro m_adultez_s 90
#macro m_vision 360
#macro m_vida 100
#macro m_velocidad 200
#macro m_errar_s 3
#macro m_finproy_s 2
#macro m_velproy 600
#macro m_oscuridad 0.5
#macro m_ping 5
#macro m_network_id 43023
#macro m_puerto 4649
#macro m_ent_diablo 0
#macro m_ent_bruja 1
#macro m_ent_esqueleto 2
#macro m_ent_lobo 3
#macro m_ent_vampiro 4
#macro m_ent_alien 5
#macro m_ent_calabaza 6
#macro m_ent_robot 7
#macro m_ent_frankenstein 8
#macro m_ent_momia 9
#macro m_ent_payaso 10
#macro m_ent_asesino 11
#macro m_ent_munneco 12
#macro m_ent_sucubo 13
#macro m_ent_incubo 14
#macro m_ent_gordo 15
#macro m_ent_pulpo 16
#macro m_ent_abominacion 17
#macro m_ent_monstruo 18
#macro m_ent_insecto 19
#macro m_ent_tronco 20
#macro m_ent_siames 21
#macro m_ent_espectro 22
#macro m_ent_harpia 23
#macro m_ent_fantasma 24
#macro m_ent_errante 25
#macro m_ent_aranna 26
#macro m_ent_ente 27
#macro m_ent_animal 28
#macro m_ent_cucaracha 29
#macro m_ent_ave 30
#macro m_ent_humano 31
#macro m_ent_total 32
#macro m_herr_nada 0
#macro m_herr_guitarra 1
#macro m_herr_tambor 2
#macro m_herr_explosivo 3
#macro m_herr_mina 4
#macro m_herr_antorcha 5
#macro m_herr_cuchillo 6
#macro m_herr_mazo 7
#macro m_herr_pico 8
#macro m_herr_hacha 9
#macro m_herr_espada 10
#macro m_herr_baculo 11
#macro m_herr_ballesta 12
#macro m_herr_lanza 13
#macro m_herr_pistola 14
#macro m_herr_escopeta 15
#macro m_herr_rifle 16
#macro m_herr_metralla 17
#macro m_herr_total 18
#macro m_herrx_escudin 18
#macro m_herrx_escudo 19
#macro m_herrx_medicina 20
#macro m_mat_nada 0
#macro m_mat_metal 1
#macro m_mat_hierro 2
#macro m_mat_maiz 3
#macro m_mat_pan 4
#macro m_mat_madera 5
#macro m_mat_tronco 6
#macro m_mat_escudin 7
#macro m_mat_escudo 8
#macro m_mat_medicina 9
#macro m_mat_bolsa 10
#macro m_luna_creciente 0
#macro m_luna_llena 1
#macro m_luna_menguante 2
#macro m_luna_negra 3
#macro m_error_version 0
#macro m_error_nombre 1
#macro m_grupo_player 0
#macro m_grupo_humano 1
#macro m_grupo_antiguo 2
#macro m_grupo_zombi 3
#macro m_grupo_especial 4
#macro m_grupo_infernal 5
#macro m_grupo_vampirico 6
#macro m_grupo_fantasmal 7
